name: lightning-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - python
  - pandas
  - ipywidgets
  - arm_pyart
  - cartopy
  - pyvista-xarray
  - ipywidgets
  - tqdm
  - pip
  - pip:
      - trame
      - trame-vtk
      - trame-vuetify
      - trame-plotly
      - sphinx-pythia-theme
      - git+https://github.com/deeplycloudy/xlma-python.git
